import { readdir, readFile, writeFile, copyFile } from 'node:fs/promises';
import { join } from 'node:path';

// Preserve Bootstrap's drawings, but ship only icons referenced by the app.
async function sources(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(entries.map(entry => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? sources(path) : /\.(html|ts)$/.test(path) ? readFile(path, 'utf8') : '';
  }));
  return files.flat().join('\n');
}

const names = [...new Set((await sources('src/app')).match(/\bbi-[a-z]+(?:-[a-z0-9]+)*/g))].sort();
let css = `/* Generated by tools/icons.mjs. Bootstrap Icons: assets/bootstrap-icons-LICENSE.txt */
.bi::before {
  content: "";
  display: inline-block;
  width: 1em;
  height: 1em;
  vertical-align: -.125em;
  background-color: currentColor;
  -webkit-mask: var(--bi-icon) no-repeat center / contain;
  mask: var(--bi-icon) no-repeat center / contain;
}
`;
for (const name of names) {
  const svg = (await readFile(`node_modules/bootstrap-icons/icons/${name.slice(3)}.svg`, 'utf8')).trim();
  css += `.${name} { --bi-icon: url("data:image/svg+xml,${encodeURIComponent(svg)}"); }\n`;
}
await writeFile('src/bootstrap-icons.css', css);
await copyFile('node_modules/bootstrap-icons/LICENSE', 'src/assets/bootstrap-icons-LICENSE.txt');
console.log(`Generated ${names.length} Bootstrap icons (${Buffer.byteLength(css)} bytes before compression).`);
